FROM golang:1.15-buster as builder

LABEL maintainer="Dody Satria <dody.satria@gmail.com>"

WORKDIR /app

COPY go.* ./
COPY . ./
RUN go mod download

RUN go build -mod=readonly -v -o server

FROM debian:buster-slim
RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/server /app/server

CMD ["/app/server"]